INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('R-880', 'AAA', 'SEGUNDO', 'MANGUERAS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('E-1999', 'AAA', 'NUÑEZ', 'LOGISTICA');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('E-2050', 'AAA', 'REYNOSO', 'ADMON');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('E-2729', 'AAA', 'HERNANDEZ GONZALEZ', 'PSICO I');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('M-3697', 'AAA', 'ORTEGA', 'HERRERIA');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4217', 'AAA', 'PEREZ', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4462', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4463', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4464', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4465', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4466', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4467', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4468', 'AAA', 'CASTAÑEDA', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4511', 'AAA', 'LOPEZ', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4576', 'AAA', 'GONZALEZ', 'PLASTICOS');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4579', 'AAA', 'LOPEZ OROZCO', 'ADMON');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4697', 'AAA', 'CHIMAL MEDINA', 'ADMON');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4698', 'AAA', 'PEREZ', 'ADMON');
INSERT INTO empleados (ID_empleado, Nombre, Apellido, Departamento) VALUES ('P-4699', 'AAA', 'RILH', 'ADMON');